# Site settings
theme: jekyll-theme-minimal
title: WiDS Texas 2021
description: A regional Women in Data Science (WiDS) event to inspire, educate & support women in the field.
logo: images/wids-2color-stacked.jpg
social_links:
   linkedin: https://www.linkedin.com/groups/9028186/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
