# Site settings
theme: jekyll-theme-minimal
title: WiDS Texas 2021
description: WiDS comes to Texas!
logo: images/wids-2color-stacked.jpg

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
